version: "3.9"
services:
  postgresql:
    container_name: zio_realworld_example_app
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: db
      POSTGES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
