name: CI

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.5
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: ./sbtx check

  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        java: ['adopt@1.8', 'adopt@1.11']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.5
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: ./sbtx test

  ci:
    runs-on: ubuntu-20.04
    needs: [lint, test]
    steps:
      - name: Aggregate job outcomes
        run: echo "ci passed"
